spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kotlin_rest_course?useTimezone=true&serverTime
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
